import { STORE_CATEGORIES, categorySlug } from "@/lib/store-categories";
import { catalogPhotoPath } from "@/lib/catalog-photo";
import { costFromSelling } from "@/lib/product-margin";

export type CatalogDraft = {
  category: string;
  title: string;
  selling: number;
  margin: number;
  blurb: string;
};

const M = [0.23, 0.24, 0.25] as const;

function m(index: number) {
  return M[index % 3];
}

const RAW: Record<string, [string, number, string][]> = {
  "Hot Selling Items": [
    ["Insulated Water Bottle", 34, "Double-wall stainless flask with a leak-lock lid for daily carry."],
    ["Everyday Carry Tumbler 32oz", 28, "Wide-mouth tumbler with a straw lid for desk and commute."],
    ["Compact Phone Tripod", 22, "Pocket tripod with a cold-shoe mount for short clips."],
    ["Magnetic Cable 3-Pack", 18, "Braided USB-C magnetic tips in three lengths."],
    ["Fold-Flat Shopping Tote", 15, "Ripstop tote that packs into its own pocket."],
    ["LED Desk Clip Light", 25, "Clamp lamp with three color temperatures."],
    ["Travel Packing Cubes Set", 32, "Four cubes with mesh lids for weekend bags."],
    ["Silicone Ice Tray with Lid", 12, "Covered tray that stacks without spilling."],
    ["Car Vent Phone Mount", 16, "One-hand magnetic mount for vent slats."],
    ["Reusable Produce Bags 8-Pack", 14, "Washable mesh bags with tare weights printed on."],
    ["Pocket Rain Poncho", 11, "Packaged poncho that fits a jacket pocket."],
    ["Cable Sleeve Organizer", 13, "Neoprene wrap for messy desk cords."],
    ["Mini Bluetooth Tracker", 29, "Coin tracker with a replaceable battery."],
    ["Collapsible Colander", 17, "Heat-safe colander that flattens for drawers."],
    ["Microfiber Cleaning Cloths 12-Pack", 19, "Lint-free cloths for glass and screens."],
    ["Portable Stain Pen", 10, "Travel stain remover for collars and cuffs."],
    ["Seat-Gap Catcher", 21, "Car-seat gap tray for phones and keys."],
    ["Stacking Spice Jars 8-Pack", 27, "Square jars with pour lids for pantry rails."],
    ["Door Draft Stopper", 23, "Weighted stopper for interior doors."],
    ["Laptop Sleeve 14-inch", 36, "Padded sleeve with a front document pocket."],
    ["Quick-Dry Hair Wrap", 20, "Terry wrap that stays on without clips."],
    ["Bottle Brush Set", 15, "Bent-handle brushes for bottles and lids."],
    ["Folding Step Stool", 39, "One-piece stool rated for kitchen shelves."],
    ["USB Rechargeable Lighter", 24, "Arc lighter with a safety lock."],
    ["Weekend Dopp Kit", 42, "Water-resistant kit with a hanging hook."],
  ],
  "Computer accessories": [
    ["Wireless Mouse", 29, "Silent-click mouse with a USB-C charge port."],
    ["USB-C Hub 7-in-1", 59, "HDMI, SD, and Ethernet hub for travel laptops."],
    ["Mechanical Keyboard 75%", 129, "Hot-swap keyboard with gasket mount."],
    ["Monitor Arm Single", 89, "Gas-spring arm for 27-inch displays."],
    ["Laptop Stand Aluminum", 45, "Ventilated stand that raises the screen to eye line."],
    ["Webcam 1080p Privacy", 69, "Built-in shutter and dual mics for calls."],
    ["USB Microphone Desktop", 99, "Cardioid mic with a gain knob and mute light."],
    ["Cable Dock Felt Tray", 22, "Desktop tray that hides brick chargers."],
    ["NVMe Enclosure USB4", 79, "Tool-free enclosure for 2280 drives."],
    ["Wireless Presenter", 34, "Laser presenter with a USB-C dongle."],
    ["Monitor Light Bar", 55, "Bias light that sits on the bezel, not the desk."],
    ["Ergonomic Wrist Rest", 26, "Memory-foam rest for full-size boards."],
    ["DisplayPort Cable 2.0", 18, "Two-meter cable for 4K 144 Hz."],
    ["Laptop Privacy Screen 15", 41, "Side-angle filter for cafe work."],
    ["USB-C GaN Charger 65W", 49, "Two-port charger for laptop plus phone."],
    ["RGB Desk Mat XXL", 32, "Stitched mat that covers keyboard and mouse."],
    ["KVM Switch 2-Port", 119, "Share one monitor and USB set between PCs."],
    ["Laptop Cooling Pad", 38, "Quiet fan pad with height stops."],
    ["SD Card Reader USB-C", 21, "UHS-II reader for photo dumps."],
    ["Bluetooth USB Adapter", 16, "Low-profile dongle for desktops."],
    ["Cable Raceway Kit", 27, "Paintable channels for wall cables."],
    ["Vertical Mouse Right", 52, "Handshake grip mouse for long sessions."],
    ["Laptop Lock Cable", 24, "Keyed lock for cafe tables."],
    ["USB Desk Fan Quiet", 31, "Oscillating fan powered from the hub."],
    ["Thunderbolt Dock", 249, "Single-cable dock with 2.5G Ethernet."],
  ],
  "Home cabinets": [
    ["Linen Duvet Cover", 129, "Stonewashed cover with interior corner ties."],
    ["Stoneware Dinner Set", 96, "Four-place stoneware in speckled glaze."],
    ["Oak Serving Board", 48, "Edge-grain board with a juice groove."],
    ["Woven Throw Blanket", 72, "Cotton throw with tassel ends."],
    ["Two-Door Accent Cabinet", 420, "Fluted-front cabinet with adjustable shelf."],
    ["Narrow Pantry Tower", 260, "Slim tower for spices and cans."],
    ["Under-Sink Organizer", 39, "Two-tier rack that clears the trap."],
    ["Wall Spice Rail", 34, "Magnetic rail for metal tins."],
    ["Entryway Shoe Cabinet", 310, "Tilt-out cabinet for eight pairs."],
    ["Bathroom Vanity Shelf", 58, "Over-toilet shelf with a towel bar."],
    ["Glass Canister Set", 44, "Three canisters with bamboo lids."],
    ["Cutlery Drawer Insert", 28, "Expandable tray for flatware."],
    ["Linen Closet Bins 3-Pack", 36, "Labeled fabric bins for sheets."],
    ["Kitchen Island Cart", 189, "Rolling cart with a butcher-block top."],
    ["Ceramic Utensil Crock", 22, "Weighted crock for spatulas."],
    ["Over-Door Pantry Caddy", 41, "Six-pocket caddy for wraps and foil."],
    ["Floating Shelf Pair", 64, "Hidden-bracket oak shelves."],
    ["Laundry Hamper Cabinet", 175, "Tilt hamper behind a shaker door."],
    ["Wine Cube Grid", 88, "Nine-bottle lattice cube."],
    ["Mug Tree Stand", 19, "Counter stand for six mugs."],
    ["Pot Lid Organizer", 25, "File-style rack for lids."],
    ["Media Console 60-inch", 540, "Cable-managed console with two cupboards."],
    ["Kids Book Bin Cabinet", 150, "Forward-facing bins for picture books."],
    ["Garage Wall Cabinet", 230, "Lockable metal cabinet for chemicals."],
    ["Glass-Front China Hutch", 890, "Lighted hutch with felt drawer."],
  ],
  "Health Products": [
    ["Daily Multivitamin", 22, "Once-daily tablets with folate and D3."],
    ["Electrolyte Stick Packs", 18, "Unflavored sticks for water bottles."],
    ["Omega-3 Softgels", 26, "Triglyceride-form fish oil."],
    ["Magnesium Glycinate", 24, "Evening capsules without oxide fillers."],
    ["Vitamin D3 K2 Drops", 21, "MCT-based drops with measured pipette."],
    ["Probiotic 20 Billion", 29, "Delayed-release capsules for travel."],
    ["Collagen Peptides Canister", 34, "Unflavored peptides that mix clear."],
    ["Iron Bisglycinate", 19, "Gentle iron with vitamin C."],
    ["Zinc Lozenges", 12, "Short-term lozenges with a mint base."],
    ["Sleep Magnesium Powder", 27, "Glycinate powder with a scoop."],
    ["Fiber Gummies", 16, "Prebiotic gummies without gelatin."],
    ["Joint Support Capsules", 31, "Glucosamine formula with turmeric."],
    ["Elderberry Syrup", 18, "Refrigerator syrup with a marked cap."],
    ["Nasal Saline Kit", 14, "Squeeze bottle with buffered packets."],
    ["Digital Thermometer", 15, "60-second oral thermometer with case."],
    ["Pulse Oximeter Clip", 28, "Finger clip with a brightness lock."],
    ["Compression Socks Pair", 23, "15-20 mmHg socks with a padded sole."],
    ["Heating Pad Wrap", 36, "Neck wrap with two heat settings."],
    ["Foam Roller Firm", 32, "36-inch roller for calves and back."],
    ["First Aid Refill Kit", 20, "Bandages and antiseptic for a home tin."],
    ["Pill Organizer Weekly", 11, "AM/PM boxes with large type."],
    ["Hand Therapy Balls", 13, "Three densities for grip work."],
    ["Blue-Light Glasses", 39, "Clear lenses with a spring hinge."],
    ["Humidifier Cool Mist", 49, "Top-fill tank with a night light."],
    ["Blood Pressure Cuff", 55, "Upper-arm cuff that stores readings."],
  ],
  "Men's clothing": [
    ["Trail Fleece Jacket", 89, "Quarter-zip fleece with a high collar."],
    ["Merino Crew Socks (3-pack)", 22, "Cushioned merino for boots and trainers."],
    ["Oxford Button-Down", 54, "Regular-fit oxford that tucks clean."],
    ["Chino Trousers Slim", 68, "Stretch chinos with a hidden coin pocket."],
    ["Merino Crew Sweater", 79, "Fine-gauge crew that layers under coats."],
    ["Selvedge Denim Jean", 128, "14-oz jean with a clean hem."],
    ["Poplin Overshirt", 72, "Utility overshirt with two chest pockets."],
    ["Performance Polo", 42, "Moisture-wicking polo with a collar stay."],
    ["Down Vest Packable", 110, "Packs into its pocket for travel."],
    ["Linen Camp Shirt", 58, "Short-sleeve linen for warm evenings."],
    ["Wool Overcoat", 240, "Knee-length coat with a storm flap."],
    ["Athletic Short 7-inch", 34, "Lined short with a zip pocket."],
    ["Ribbed Beanie", 18, "Merino blend beanie without a pom."],
    ["Canvas Work Jacket", 96, "Washed canvas with elbow patches."],
    ["Dress Belt 35mm", 45, "Veg-tan belt with a brushed buckle."],
    ["Boxer Brief 3-Pack", 28, "Modal blend with a no-roll waist."],
    ["Rain Shell Jacket", 149, "Two-layer shell with pit zips."],
    ["Knit Polo Long Sleeve", 61, "Pique knit for cooler days."],
    ["Tapered Sweatpant", 48, "French terry pant with ankle cuffs."],
    ["Flannel Shirt Regular", 52, "Brushed flannel in a two-color check."],
    ["Leather Derby Shoe", 175, "Goodyear-welt derby for office days."],
    ["Running Tee Seamless", 36, "Seamless tee with mesh underarms."],
    ["Quilted Liner Jacket", 88, "Lightweight liner under shells."],
    ["Wool-Blend Trouser", 92, "Unfinished hem ready for tailoring."],
    ["Cashmere Scarf", 130, "Plain-weave scarf with hand-rolled edges."],
  ],
  "Women's clothing": [
    ["Linen Midi Dress", 68, "Wrap midi with side pockets."],
    ["Wide-Leg Trouser", 74, "High-rise trouser with a front crease."],
    ["Silk Camisole", 46, "Bias-cut cami with adjustable straps."],
    ["Cropped Cardigan", 58, "Short cardigan that sits at the waist."],
    ["Denim Jacket Relaxed", 82, "Washed jacket with dropped shoulders."],
    ["Pleated Midi Skirt", 64, "Satin pleats with an elastic back."],
    ["Trench Coat Classic", 198, "Cotton gabardine trench with a belt."],
    ["Rib Knit Set", 72, "Matching top and skirt in cotton rib."],
    ["Blouse with Tie Neck", 54, "Georgette blouse that tucks into trousers."],
    ["Yoga Legging Pocket", 48, "High-rise legging with a side pocket."],
    ["Wool Wrap Coat", 260, "Cocoon coat with hidden snaps."],
    ["Poplin Shirt Dress", 79, "Shirt dress with a self belt."],
    ["Cashmere Crew", 160, "Lightweight crew for layering."],
    ["Tailored Blazer", 145, "Single-button blazer with stretch lining."],
    ["Slip Skirt 90s", 52, "Bias slip that hits mid-calf."],
    ["Merino Turtleneck", 70, "Fine knit turtleneck without itch."],
    ["Linen Wide Short", 44, "Paper-bag short for warm travel."],
    ["Evening Jumpsuit", 128, "Wide-leg jumpsuit with a covered zip."],
    ["Down Puffer Crop", 170, "Cropped puffer that sits above jeans."],
    ["Pointelle Knit Top", 39, "Short-sleeve pointelle for layering."],
    ["Suede Loafer", 155, "Stacked-heel loafer with a penny slot."],
    ["Cotton Poplin Shirt", 49, "Crisp shirt with a hidden placket."],
    ["Maxi Knit Dress", 88, "Column knit with a side slit."],
    ["Leather Belt Mini", 36, "1-inch belt for dresses."],
    ["Organza Occasion Top", 96, "Sheer overlay top for evenings."],
  ],
  "Snacks and desserts": [
    ["Almond Cookie Pack", 12, "Butter cookies with toasted almonds."],
    ["Dark Chocolate Bark", 14, "Seventy-percent bark with sea salt."],
    ["Honey Sesame Sticks", 11, "Crunchy sticks with toasted sesame."],
    ["Freeze-Dried Strawberry", 13, "Whole slices that stay crisp."],
    ["Pistachio Nougat Bar", 16, "Soft nougat with pistachio pieces."],
    ["Matcha Shortbread Tin", 18, "Tin of shortbread with ceremonial-grade matcha."],
    ["Chili Mango Slices", 10, "Dried mango with mild chili dust."],
    ["Caramel Pretzel Mix", 15, "Sweet-salt mix for movie nights."],
    ["Olive Oil Crackers", 12, "Thin crackers for cheese boards."],
    ["Coconut Macaroon Box", 17, "Chewy macaroons without corn syrup."],
    ["Trail Mix No Peanut", 13, "Cashew-forward mix for offices."],
    ["Yuzu Gummy Cubes", 11, "Citrus gummies with a tart coat."],
    ["Brown Butter Blondies", 19, "Four blondies wrapped for gifting."],
    ["Espresso Bean Chocolate", 14, "Dark cups with a whole bean."],
    ["Rice Cracker Sampler", 12, "Soy, seaweed, and plain crackers."],
    ["Maple Pecan Clusters", 16, "Oven clusters with grade-A maple."],
    ["Raspberry Fruit Leather", 10, "Two-ingredient leather strips."],
    ["Salted Toffee Shards", 15, "English toffee with almond bits."],
    ["Black Sesame Cookies", 13, "Crisp cookies with a tahini finish."],
    ["Honeycomb Chocolate Bar", 14, "Aerated honeycomb in milk chocolate."],
    ["Wasabi Pea Jar", 11, "Oven peas with real wasabi heat."],
    ["Lemon Posset Cups", 18, "Two chilled cups ready to serve."],
    ["Date Energy Bites", 12, "No-bake bites with cacao nibs."],
    ["Earl Grey Tea Cookies", 13, "Bergamot shortbread rounds."],
    ["Gift Dessert Sampler", 28, "Five sweets in a paper tray."],
  ],
  "Mobile accessories": [
    ["Noise-Cancel Earbuds", 89, "In-ear buds with a charging case."],
    ["MagSafe Wallet Clip", 32, "Leather wallet that snaps to the back."],
    ["Silicone Case Clear", 18, "Yellowing-resistant case with lip protection."],
    ["Tempered Glass 2-Pack", 14, "Easy-tray glass for the latest screen."],
    ["Braided USB-C Cable 2m", 16, "Charge-and-sync cable with strain relief."],
    ["Car Charger 45W Dual", 27, "Two-port charger for cabin sockets."],
    ["Pop Grip Ring", 12, "Low-profile ring that sits flat."],
    ["Wireless Pad 15W", 29, "Qi2 pad with a cool-touch surface."],
    ["Phone Lanyard Crossbody", 19, "Adjustable lanyard with a pad patch."],
    ["Lens Clip Kit", 24, "Macro and wide clips for social stills."],
    ["Battery Case Slim", 49, "Thin case with a status LED."],
    ["Lightning to USB-C Dongle", 15, "Short adapter for older accessories."],
    ["Car Mount Mag Dashboard", 26, "Sticky-base mount that holds in heat."],
    ["Earbud Tips Foam", 11, "Memory-foam tips in three sizes."],
    ["Selfie Stick Mini", 21, "Extends to arm length without a tripod."],
    ["USB-C Headphones Wired", 23, "In-line mic for calls on USB-C phones."],
    ["Screen Cleaner Kit", 10, "Spray and cloth sized for pockets."],
    ["Mag Power Bank 5000", 39, "Snap bank that charges while you walk."],
    ["SIM Tool and Tray Case", 10, "Tiny case for travel SIMs."],
    ["Phone Stand Folding", 17, "Aluminum stand for video calls."],
    ["Camera Control Pouch", 22, "Pouch for phones with large camera bumps."],
    ["USB-C Hub Phone", 35, "HDMI-out hub that draws from the phone."],
    ["Waterproof Pouch Float", 16, "IPX8 pouch with a lanyard."],
    ["Gaming Trigger Pair", 28, "Capacitive triggers for two-thumb play."],
    ["Desk Charging Stand", 33, "Nightstand stand with a watch puck slot."],
  ],
  "Children's toys": [
    ["Wooden Puzzle Set", 18, "Chunky animal puzzle with knobs."],
    ["Magnetic Tile Starter", 42, "32 tiles with two figure wheels."],
    ["Plush Night Fox", 24, "Weighted plush with a dimmable belly light."],
    ["Wooden Train Set", 55, "Figure-eight track with a magnetic engine."],
    ["Stacking Rainbow Arch", 29, "Seven arches in water-based stain."],
    ["Balance Bike Mini", 89, "No-pedal bike with a limited steer."],
    ["Play Kitchen Utensils", 21, "Felt food and wooden spoons."],
    ["Building Bricks 200", 34, "Classic bricks compatible with major sets."],
    ["Kite with Line", 16, "Single-line kite for parks."],
    ["Water Beads Kit", 13, "Non-toxic beads with a scoop tray."],
    ["Doctor Kit Wooden", 27, "Stethoscope and thermometer in a case."],
    ["Marble Run Starter", 46, "Click-together run with glass marbles."],
    ["Bubble Machine Portable", 22, "Battery wand that makes a stream."],
    ["Dress-Up Cape", 19, "Reversible cape with a snap collar."],
    ["Shape Sorter Box", 20, "Five shapes with a quiet close lid."],
    ["Remote Dino Walker", 38, "Walking figure with a simple remote."],
    ["Art Easel Tabletop", 31, "Two-sided easel with clip paper."],
    ["Jump Rope Kids", 12, "Adjustable rope with soft handles."],
    ["Foam Block City", 36, "Oversized foam bricks for forts."],
    ["Science Crystal Kit", 25, "Grow a crystal with a display dome."],
    ["Musical Keyboard 32", 44, "Mini keys with a record button."],
    ["Pull-Along Snail", 17, "Wooden snail that bobs while walking."],
    ["Board Game First", 23, "Cooperative game with picture cards."],
    ["Outdoor Croquet Set", 49, "Short mallets for backyard play."],
    ["Telescope Kids 50mm", 58, "Table telescope with a moon map."],
  ],
  Beverages: [
    ["Sparkling Lemon Drink", 10, "Light sparkle with real lemon peel."],
    ["Cold Brew Concentrate", 14, "Bottle that dilutes one-to-one."],
    ["Jasmine Green Tins", 16, "Loose leaf in a resealable tin."],
    ["Ginger Turmeric Tonic", 12, "Still tonic with a pepper finish."],
    ["Oat Barista Carton", 11, "Steams for cafe drinks at home."],
    ["Yuzu Soda 4-Pack", 15, "Cans with a dry citrus profile."],
    ["Chamomile Night Tins", 13, "Caffeine-free flowers for evenings."],
    ["Espresso Capsules 20", 18, "Aluminum pods for home machines."],
    ["Coconut Water Tetra", 11, "No-added-sugar cartons."],
    ["Hibiscus Cooler", 12, "Tart cooler that pours over ice."],
    ["Maple Cold Coffee", 14, "Ready-to-drink coffee with maple."],
    ["Kombucha Ginger", 13, "Small-batch bottles with a live culture."],
    ["Mineral Water Case", 19, "Glass bottles with a mineral finish."],
    ["Matcha Latte Mix", 17, "Whisk-ready powder with oat creamer."],
    ["Chai Concentrate", 15, "Spiced concentrate for milk or water."],
    ["Berry Electrolyte Drink", 11, "Low-sugar bottle for gym bags."],
    ["White Tea Sachets", 14, "Pyramid bags that stay intact."],
    ["Tonic Syrup Small", 16, "Quinine syrup for homemade spritz."],
    ["Roasted Barley Tea", 12, "Caffeine-free barley for kettles."],
    ["Sparkling Peach Can", 10, "Soft peach with fine bubbles."],
    ["Cocoa Drinking Mix", 15, "Dutch cocoa for hot cups."],
    ["Lime Cordial Bottle", 13, "Cordial for sodas and mocktails."],
    ["Nitro Coffee Can", 14, "Nitrogenated coffee without dairy."],
    ["Herbal Digestif Tea", 13, "Fennel and mint after meals."],
    ["Tasting Flight Sodas", 22, "Six small bottles of house sodas."],
  ],
  "Office supplies": [
    ["Desk Organizer Tray", 16, "Three-compartment tray for pens and clips."],
    ["Notebook A5 Dotted", 14, "Lay-flat notebook with numbered pages."],
    ["Gel Pen Set 10", 12, "Fine gel pens that do not skip."],
    ["Stapler Low Force", 18, "Half-strip stapler for thick packets."],
    ["Monitor Riser Drawer", 36, "Bamboo riser with a hidden drawer."],
    ["Label Maker Compact", 29, "QWERTY maker with a rechargeable battery."],
    ["File Folders Color 25", 11, "1/3-cut folders in five colors."],
    ["Whiteboard Desktop", 22, "A3 board with a marker ledge."],
    ["Binder Clips Heavy", 10, "Assorted clips in a tin."],
    ["Desk Lamp Task", 45, "Arm lamp with a USB-C port."],
    ["Paper Tray Trio", 27, "Stacking trays for incoming mail."],
    ["Scissors Titanium", 13, "Soft-grip shears for card stock."],
    ["Sticky Notes Recycled", 10, "Lined notes in a muted palette."],
    ["Cable Clips Adhesive", 11, "Drop clips for the desk edge."],
    ["Document Case Expand", 19, "13-pocket case for travel files."],
    ["Printer Paper 500", 12, "Bright-white ream for laser and inkjet."],
    ["Mouse Pad Stitched", 14, "Cloth pad with a non-slip base."],
    ["Timer Cube", 16, "Four-sided timer for focus blocks."],
    ["Pen Cup Concrete", 18, "Weighted cup that will not tip."],
    ["Hole Punch 3-Ring", 15, "Adjustable punch for binders."],
    ["Planner Weekly Undated", 20, "Undated weeks with a habit strip."],
    ["Highlighter Dual Tip", 11, "Chisel and fine in four colors."],
    ["USB Flash 128GB", 24, "Metal stick with a keyring loop."],
    ["Shredder Cross-Cut", 79, "Six-sheet shredder with a bin window."],
    ["Conference Notepad Folio", 32, "Zip folio with a pad and pockets."],
  ],
  "Digital products": [
    ["Portable SSD 1TB", 79, "Bus-powered SSD in a shock sleeve."],
    ["microSD 256GB A2", 28, "High-endurance card for action cameras."],
    ["Streaming Stick 4K", 49, "HDMI stick with a voice remote."],
    ["eReader 6-inch", 129, "Front-lit reader with weeks of battery."],
    ["Action Camera 4K", 199, "Waterproof camera with a mount kit."],
    ["Wireless Presenter Click", 34, "Clicker with a USB-C receiver."],
    ["MIDI Keyboard 25", 89, "Mini keys with aftertouch for sketches."],
    ["Capture Card HDMI", 119, "1080p60 capture for laptops."],
    ["Smart Plug 2-Pack", 22, "Energy-monitor plugs for lamps."],
    ["Wi-Fi Mesh Node", 149, "Add-on node for a three-room mesh."],
    ["Dash Cam Front", 99, "1080p cam with a capacitor, not a cell."],
    ["Photo Frame Wi-Fi", 89, "Cloud frame that crops to the screen."],
    ["Bluetooth Speaker Mini", 39, "Pocket speaker with a lanyard."],
    ["USB DAC Dongle", 45, "Headphone dongle with a volume rocker."],
    ["Smart Scale Bluetooth", 36, "Floor scale that logs to a phone."],
    ["GPS Logger Keychain", 54, "Offline logger for trips."],
    ["LED Light Panel", 62, "Dimmable panel for desk video."],
    ["Wireless HDMI Kit", 179, "Sender and receiver for a TV across the room."],
    ["NAS 2-Bay Empty", 249, "Diskless bay for home backups."],
    ["Stylus Pencil USB-C", 42, "Tilt stylus for current tablets."],
    ["VR Facial Interface", 29, "Washable interface for a headset."],
    ["Streaming Microphone Arm", 48, "Boom arm with hidden cable channel."],
    ["Game Capture Remote", 21, "Bluetooth remote for console clips."],
    ["Portable Monitor 15", 229, "USB-C monitor that draws from the laptop."],
    ["Smart Doorbell Wired", 159, "Wired bell with a package zone."],
  ],
  "Beauty and skincare": [
    ["Brightening C Serum", 38, "Stable ascorbate serum in a dropper."],
    ["Mineral SPF 50", 28, "Zinc lotion that leaves little cast."],
    ["Overnight Repair Cream", 52, "Ceramide cream for night use."],
    ["Gentle Cleansing Balm", 24, "Balm that rinses without film."],
    ["Hyaluronic Mist", 18, "Fine mist for desks and flights."],
    ["Retinol Night Caps", 46, "Encapsulated retinol in airless pumps."],
    ["Clay Mask Jar", 22, "Kaolin mask with a wooden spatula."],
    ["Lip Balm Trio", 14, "Unscented, mint, and berry tins."],
    ["Eye Cream Caffeine", 32, "Cooling cream for morning puffiness."],
    ["Body Oil Dry", 26, "Fast-absorbing oil with a pump."],
    ["Toner Pad Jar", 19, "Exfoliating pads with a tweezer lid."],
    ["Brow Gel Clear", 16, "Hold gel with a tiny spoolie."],
    ["Mineral Concealer Pot", 21, "Buildable concealer with a mirror."],
    ["Hair Oil Ends", 23, "Lightweight oil for lengths only."],
    ["SPF Stick Face", 17, "Zinc stick for ears and nose."],
    ["Sheet Mask Box 5", 20, "Five cellulose masks in foil."],
    ["Cuticle Oil Pen", 12, "Pen applicator for travel."],
    ["Body Polish Grain", 18, "Sugar polish with a pump jar."],
    ["Deodorant Cream Jar", 15, "Bicarb-free cream in a glass jar."],
    ["Face Cloth Set", 13, "Four muslin cloths for balm cleanse."],
    ["Tinted Moisturizer", 29, "Sheer tint with SPF 30."],
    ["Scalp Serum Dropper", 34, "Leave-in serum for the hairline."],
    ["Makeup Sponge 4-Pack", 11, "Latex-free sponges that bounce back."],
    ["Night Serum Peptide", 58, "Peptide serum in a UV bottle."],
    ["Travel Minis Kit", 36, "Cleanser, cream, and SPF in TSA sizes."],
  ],
  "Mother and baby products": [
    ["Silicone Feeding Set", 32, "Suction bowl, spoon, and bib."],
    ["Newborn Envelope Onesie", 26, "Envelope-neck onesie in two-pack."],
    ["Muslin Swaddle 2-Pack", 24, "Open weaves that stay cool."],
    ["Bottle Brush Compact", 12, "Sponge brush with a teat cleaner."],
    ["Nursing Pillow", 48, "Firm pillow with a removable cover."],
    ["Pacifier Clip Pair", 14, "Breakaway clips with silicone beads."],
    ["Diaper Caddy Portable", 29, "Felt caddy that stands in the car."],
    ["Baby Nail Trimmer", 16, "LED trimmer with three buffers."],
    ["Burp Cloth 5-Pack", 18, "Absorbent cloths with a decorative edge."],
    ["Silicone Teether Keys", 11, "Freezer-safe keys on a ring."],
    ["Stroller Cup Holder", 15, "Clamp holder for bottles."],
    ["White Noise Machine", 39, "Non-looping sounds with a night light."],
    ["Changing Pad Portable", 22, "Wipe-clean pad that folds into a clutch."],
    ["Baby Thermometer No-Touch", 28, "Forehead reading in one second."],
    ["Cotton Bibs 8-Pack", 17, "Snaps at the back, not velcro."],
    ["Bottle Warmer Travel", 34, "USB warmer for night feeds."],
    ["Crib Sheet 2-Pack", 25, "Fitted sheets with deep corners."],
    ["Infant Carrier Wrap", 54, "Stretch wrap with a marked waist."],
    ["Bath Support Seat", 21, "Mesh seat for supervised baths."],
    ["Milk Storage Bags", 13, "Double-zip bags with a write panel."],
    ["Stroller Rain Cover", 19, "Clear cover with air vents."],
    ["Teething Gel Free", 12, "Cooling gel without benzocaine."],
    ["Play Gym Mat", 58, "Machine-wash mat with wooden gym."],
    ["Car Seat Mirror", 16, "Rear-facing mirror for the headrest."],
    ["Toddler Straw Cup", 14, "Weighted straw cup that does not leak."],
  ],
  "Jewelry and watches": [
    ["Silver Pendant Necklace", 54, "Cable chain with a disc pendant."],
    ["Gold-Fill Hoop Pair", 48, "Hinged hoops that sit close to the ear."],
    ["Pearl Stud Earrings", 62, "Freshwater pearls on silver posts."],
    ["Minimal Cuff Bracelet", 39, "Open cuff that stacks with others."],
    ["Signet Ring Brushed", 72, "Oval signet for engraving later."],
    ["Leather Watch 38mm", 189, "Sunburst dial with a quick-release strap."],
    ["Tennis Bracelet Cubic", 86, "Four-prong setting on a box clasp."],
    ["Layering Chain Set", 44, "Three lengths in one pouch."],
    ["Chronograph 42mm", 320, "Quartz chrono with a tachymeter bezel."],
    ["Birthstone Charm", 28, "Small charm with a split ring."],
    ["Bar Necklace Vertical", 51, "Vertical bar that takes initials."],
    ["Mesh Watch Two-Tone", 210, "Slim mesh bracelet with a clasp lock."],
    ["Huggie Hoops Pair", 36, "Clicker hoops for second holes."],
    ["Locket Heart Small", 58, "Two-photo locket on an 18-inch chain."],
    ["Cufflinks Brushed Pair", 64, "Brushed steel faces for dress shirts."],
    ["Anklet Satellite", 26, "Delicate satellite chain for summer."],
    ["Field Watch 40mm", 275, "Lumed hands and a NATO strap."],
    ["Stacking Ring Trio", 42, "Three thin bands in mixed metals."],
    ["Drop Earring Linear", 47, "Bar drops with a secure nut."],
    ["Bangle Hinged", 69, "Polished bangle with a safety latch."],
    ["Pendant Compass", 55, "Working compass on a leather cord."],
    ["Solar Watch 36mm", 240, "Light-powered movement, no battery swap."],
    ["Curb Chain Necklace", 88, "Medium curb that wears alone."],
    ["Ear Cuff No Pierce", 22, "Single cuff for the helix."],
    ["Dress Watch 34mm", 410, "Leather-strap dress watch with a sapphire crystal."],
  ],
  "Luxury goods": [
    ["Silk Evening Scarf", 120, "Hand-rolled silk with a quiet print."],
    ["Cashmere Throw", 380, "Heavy throw with blanket-stitch edges."],
    ["Leather Weekender", 540, "Full-grain bag with a shoe compartment."],
    ["Fountain Pen Resin", 290, "Piston filler with an 18k nib."],
    ["Crystal Decanter", 210, "Stoppered decanter for spirits."],
    ["Suede Opera Gloves", 160, "Wrist gloves lined in silk."],
    ["Gold-Plate Desk Clock", 250, "Quiet quartz clock with a leather face."],
    ["Cashmere Polo", 320, "Short-sleeve polo in two-ply yarn."],
    ["Crocodile-Print Card Case", 180, "Embossed case with a cash slot."],
    ["Silk Pajama Set", 260, "Piping set with a drawstring pant."],
    ["Marble Wine Cooler", 340, "Carved cooler that holds one bottle."],
    ["Private Salon Armchair", 2500, "Club chair in aniline leather with a down cushion."],
    ["Bespoke Tuxedo Set", 1800, "Jacket, trouser, and silk peak lapel."],
    ["Titanium Sunglasses", 420, "Rimless titanium with nylon lenses."],
    ["Alpaca Overcoat", 890, "Unstructured coat with horn buttons."],
    ["Porcelain Tea Set", 310, "Four cups and a pot in a gift box."],
    ["Oud Candle Large", 75, "Sixty-hour candle in a heavy glass."],
    ["Mother-of-Pearl Cuff", 230, "Inlay cuff with a hidden hinge."],
    ["Linen Tablecloth Hem", 140, "Stonewashed cloth for eight seats."],
    ["Watch Winder Double", 560, "Quiet winder with two pillows."],
    ["Grand Complication Watch", 4200, "Exhibition-back watch with a moon phase."],
    ["Leather Valet Tray", 110, "Catchall stitched in saddle thread."],
    ["Hand-Finished Travel Trunk", 3500, "Canvas-and-leather trunk with brass latches."],
    ["Crystal Picture Frame", 150, "Beveled frame for a 5x7 print."],
    ["Atelier Diamond Brooch", 5000, "Certified stone set in a platinum bar."],
  ],
  "Children's clothing": [
    ["Organic Cotton Onesie", 26, "Envelope neck for easy changes."],
    ["Soft Denim Overall", 34, "Adjustable overall with easy snaps."],
    ["Rain Jacket Kids", 42, "Packable shell with reflective tape."],
    ["Merino Base Layer", 38, "Top and pant set for cold days."],
    ["School Polo Pair", 24, "Two polos that take a crest."],
    ["Fleece Zip Hoodie", 32, "Full-zip hoodie with thumb holes."],
    ["Tutu Skirt Play", 22, "Soft tulle over cotton shorts."],
    ["Canvas Sneaker Kids", 36, "Machine-wash sneakers with a toe cap."],
    ["Pajama Set Stars", 28, "Long-sleeve set with a non-slip sole."],
    ["Swim Rash Guard", 25, "UPF top for lessons."],
    ["Corduroy Jumper", 39, "Jumper dress with a button strap."],
    ["Snow Bib Toddler", 54, "Insulated bib with a grow cuff."],
    ["Cotton Legging 3-Pack", 21, "Everyday leggings in three colors."],
    ["Button Cardigan", 29, "Crew cardigan for school photos."],
    ["Cargo Short Kids", 23, "Twins pockets that actually close."],
    ["Sun Hat Wide", 18, "Chin-strap hat with a neck flap."],
    ["Party Dress Poplin", 44, "Sash dress with a cotton lining."],
    ["Graphic Tee Two-Pack", 20, "Heavy cotton tees that keep shape."],
    ["Knit Beanie Kids", 14, "Soft brim that stays out of eyes."],
    ["School Trouser Pair", 30, "Reinforced knees for playgrounds."],
    ["Bathrobe Hooded", 27, "After-swim robe with a name tab."],
    ["Slip-On Boot Kids", 40, "Easy boot with a side zip."],
    ["Tights Cable Knit", 16, "Warm tights that do not sag."],
    ["Bomber Jacket Mini", 48, "Light bomber for spring."],
    ["Family Matching Pajama", 35, "Kid set that matches adult prints."],
  ],
  "Men's bags": [
    ["Alpine Daypack 22L", 64, "Panel-load pack with a laptop sleeve."],
    ["Messenger Waxed Canvas", 88, "Flap messenger with a trolley strap."],
    ["Leather Brief Slim", 210, "One-compartment brief for a 14-inch laptop."],
    ["Gym Duffel 35L", 54, "Shoe tunnel duffel that stands open."],
    ["Sling Bag 5L", 39, "Crossbody sling with a water bottle loop."],
    ["Weekender Canvas 45L", 96, "Unstructured holdall with a wet pocket."],
    ["Toiletry Hang Kit", 32, "Hook kit with clear bottles."],
    ["Camera Sling Insert", 44, "Padded insert that drops into a sling."],
    ["Laptop Backpack 20L", 79, "Clamshell pack with a luggage pass-through."],
    ["Belt Bag Leather", 48, "Waist bag that also wears as a sling."],
    ["Garment Bag Fold", 72, "Folds twice for overhead bins."],
    ["Tool Roll Canvas", 28, "Roll for cables and bits."],
    ["Tote Heavy Canvas", 36, "Open tote with a snap key leash."],
    ["Rolling Carry-On 40L", 180, "Two-wheel carry-on within airline size."],
    ["Field Bag Satchel", 92, "Satchel with a map pocket."],
    ["Hip Pack Trail", 34, "Bounce-free pack for runs."],
    ["Laptop Sleeve 16", 29, "Neoprene sleeve with a zipper garage."],
    ["Drawstring Sport", 22, "Cinch bag with a zip valuables pocket."],
    ["Brief Backpack Convert", 140, "Handles that hide for backpack mode."],
    ["Passport Wallet RFID", 26, "Travel wallet with a sim slot."],
    ["Cooler Tote Soft", 58, "Insulated tote for day trips."],
    ["Range Bag Compact", 46, "Divided bag for range days."],
    ["Bike Pannier Single", 69, "Waterproof pannier with a roll top."],
    ["Attaché Zip Folio", 84, "Slim folio for a tablet and papers."],
    ["Dopp and Shoe Bundle", 61, "Matched kit and shoe bag."],
  ],
  "Women's bags": [
    ["Crossbody Tote", 48, "Everyday tote with a zip top."],
    ["Hobo Shoulder Soft", 72, "Slouch hobo that holds a small bottle."],
    ["Mini Top-Handle", 86, "Structured mini for evenings."],
    ["Backpack City 12L", 64, "Anti-theft zip on a slim backpack."],
    ["Clutch Envelope", 34, "Fold-over clutch with a wrist strap."],
    ["Bucket Bag Draw", 78, "Drawstring bucket with a pouch insert."],
    ["Shopper Leather Large", 160, "Unlined shopper that slumps nicely."],
    ["Belt Bag Quilt", 42, "Quilted belt bag with a coin zip."],
    ["Camera Bag Mini", 54, "Box bag that wears crossbody."],
    ["Weekender Soft 30L", 98, "Light holdall with a trolley sleeve."],
    ["Card Case Flap", 28, "Flap case for six cards."],
    ["Saddle Bag Classic", 110, "Flap saddle with a turn lock."],
    ["Tote Nylon Packable", 36, "Packs into a pocket for extra shopping."],
    ["Evening Bag Bead", 70, "Beaded bag with a chain strap."],
    ["Laptop Tote 15", 88, "Work tote with a padded sleeve."],
    ["Phone Bag Leather", 32, "Just-phone bag with a card slot."],
    ["Barrel Bag Small", 66, "Cylinder bag with side rings."],
    ["Picnic Basket Tote", 52, "Structured tote that stands on a blanket."],
    ["Convertible Backpack", 94, "Straps hide for a tote look."],
    ["Frame Bag Top", 120, "Kiss-lock frame with a mirror pocket."],
    ["Straw Shoulder", 44, "Summer shoulder with a cloth lining."],
    ["Gym Tote Shoe", 58, "Bottom shoe garage that unzips."],
    ["Mini Backpack Leather", 130, "Structured mini with brass feet."],
    ["Pouch Trio Travel", 29, "Three pouches that clip together."],
    ["Doctor Bag Mini", 150, "Top-frame bag with a center strap."],
  ],
  "Fitness Equipment": [
    ["Adjustable Kettlebell", 79, "Plate-loaded bell for small rooms."],
    ["Resistance Band Set", 29, "Five bands with door anchor and handles."],
    ["Yoga Mat Pro", 58, "6mm mat with alignment marks."],
    ["Jump Rope Steel", 19, "Bearing rope with a 3-meter cable."],
    ["Adjustable Dumbbell Pair", 249, "Selector pair that stores upright."],
    ["Foam Roller Grid", 32, "Textured roller for calves."],
    ["Ab Wheel Wide", 24, "Dual-wheel roller with knee pad."],
    ["Pull-Up Bar Door", 36, "No-screw bar with a grip tape wrap."],
    ["Massage Gun Mini", 89, "Quiet percussion unit with four heads."],
    ["Balance Trainer Dome", 64, "Inflatable dome with resistance tubes."],
    ["Weight Bench Fold", 129, "Folding bench with three inclines."],
    ["Gymnastic Rings Wood", 44, "Numbered straps for even height."],
    ["Rowing Machine Compact", 890, "Magnetic rower that stands to store."],
    ["Ankle Weight Pair", 22, "Adjustable pairs for walk days."],
    ["Push-Up Board", 27, "Color-coded board for hand positions."],
    ["Speed Ladder", 18, "Flat ladder that packs small."],
    ["Slam Ball 10lb", 34, "No-bounce ball for conditioning."],
    ["Yoga Block Pair", 16, "Cork blocks that do not slip."],
    ["Heart Strap Monitor", 49, "Chest strap that talks to gym screens."],
    ["Dip Station Mini", 75, "Parallel bars for home dips."],
    ["Battle Rope 30ft", 58, "Covered rope with vinyl ends."],
    ["Stationary Bike Fold", 320, "X-bike with a quiet flywheel."],
    ["Medicine Ball 8lb", 28, "Textured ball for partner throws."],
    ["Calf Stretch Wedge", 21, "Slant board for after runs."],
    ["Power Rack Compact", 1500, "Half rack with pull-up and safety pins."],
  ],
};

export function flattenDistributionCatalog(): CatalogDraft[] {
  const rows: CatalogDraft[] = [];
  for (const category of STORE_CATEGORIES) {
    const items = RAW[category];
    if (!items || items.length < 25) {
      throw new Error(`Catalog incomplete for ${category}`);
    }
    items.slice(0, 25).forEach((item, index) => {
      rows.push({
        category,
        title: item[0],
        selling: item[1],
        margin: m(index),
        blurb: item[2],
      });
    });
  }
  return rows;
}

export const ON_SHELF_TITLES = new Set([
  "Insulated Water Bottle",
  "Woven Throw Blanket",
  "Jump Rope Steel",
]);

export const GROWTH_MAX_PRODUCTS = 800;

export function catalogSku(category: string, index: number) {
  return `DC-${categorySlug(category).slice(0, 18)}-${String(index + 1).padStart(2, "0")}`;
}

export function pricedDistributionCatalog() {
  const counts: Record<string, number> = {};
  return flattenDistributionCatalog().map((draft) => {
    const index = counts[draft.category] ?? 0;
    counts[draft.category] = index + 1;
    return rememberCatalogRow(pricedCatalogRow(draft, index));
  });
}

export function pricedCatalogRow(draft: CatalogDraft, index: number) {
  const priced = costFromSelling(draft.selling, draft.margin);
  const sku = catalogSku(draft.category, index);
  return {
    ...draft,
    ...priced,
    sku,
    image: catalogPhotoPath(sku),
    description: `${draft.title}. ${draft.blurb} Cost and selling prices are stored separately so listing status can change without duplicating the SKU.`,
  };
}

export const EXTRA_STORE_PRODUCTS: {
  merchant: number;
  category: string;
  title: string;
  selling: number;
  blurb: string;
}[] = [
  { merchant: 1, category: "Home cabinets", title: "Cedar Linen Chest", selling: 310, blurb: "Aromatic chest for off-season bedding." },
  { merchant: 1, category: "Home cabinets", title: "Austin Bar Cabinet", selling: 470, blurb: "Latched cabinet with a stemware rail." },
  { merchant: 2, category: "Beauty and skincare", title: "Lumen Overnight Mask", selling: 44, blurb: "Sleep mask with a rosewater finish." },
  { merchant: 2, category: "Beauty and skincare", title: "Lumen Lip Treatment", selling: 18, blurb: "Overnight treatment in a squeeze tube." },
  { merchant: 3, category: "Fitness Equipment", title: "Atlas Wall Ball 12lb", selling: 42, blurb: "Textured wall ball for throws." },
  { merchant: 3, category: "Fitness Equipment", title: "Atlas Gym Chalk Block", selling: 12, blurb: "Carbonate block for heavy pulls." },
  { merchant: 4, category: "Mother and baby products", title: "Willow Travel Crib Sheet", selling: 22, blurb: "Fitted sheet for pack-and-play." },
  { merchant: 5, category: "Computer accessories", title: "BrightByte USB-C Dock Mini", selling: 139, blurb: "Travel dock archived with the suspended store." },
];

const catalogBySku = new Map<string, { sku: string; title: string; category: string }>();

function rememberCatalogRow<T extends { sku: string; title: string; category: string }>(row: T): T {
  catalogBySku.set(row.sku, { sku: row.sku, title: row.title, category: row.category });
  return row;
}

export function catalogRowForSku(sku: string) {
  if (catalogBySku.size === 0) {
    pricedDistributionCatalog();
    pricedExtraProducts();
  }
  return catalogBySku.get(sku);
}

export function pricedExtraProducts() {
  return EXTRA_STORE_PRODUCTS.map((item, index) => {
    const sku = `EX-${item.merchant + 1}-${categorySlug(item.title).slice(0, 22)}`;
    const priced = costFromSelling(item.selling, m(index));
    return rememberCatalogRow({
      ...item,
      ...priced,
      sku,
      image: catalogPhotoPath(sku),
      description: `${item.title}. ${item.blurb} Cost, selling price, and listing status share one product record.`,
    });
  });
}
